POST  http://localhost:3003/api/blogs
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5vT25lIiwiaWQiOiI1ZWEwYTdiYzM4NDhhMzBhZGNlZTA5N2EiLCJpYXQiOjE1ODc1OTAxODF9.I0mA1NgZ-A41PE-hpaiPFm8LPgThMEQpTGNOFKk5Qw0


{
  "title": "I again created a another token with a middleware, and it is amazing",
  "url": "http://localhost:3003/api/blogs",
  "likes": 23
}